package com.bytesw.platform.utilities;

public enum SeccionFormularioCuenta {
	CLIENTE_PRODUCTO,
	DATOS_GENERALES,
	DATO_CHEQUERA,
	DATO_INTERES,
	BENEFICIARIOS,
	BENEFICIARIOS_FINALES,
	FIRMAS,
	PLAZO_FIJO,
	SERVICIOS_ELECTRONICOS,
	PERSONAS_ASOCIADAS,
	CUENTAS_TRASLADOS,
	CAMBIO_DE_NOMBRE,
	CAMBIO_DE_IDENTIFICACION
}
