export enum AccountFormSection {
  CLIENTE_PRODUCTO,
  DATOS_GENERALES,
  DATO_CHEQUERA,
  DATO_INTERES,
  BENEFICIARIOS,
  BENEFICIARIOS_FINALES,
  FIRMAS,
  PLAZO_FIJO,
  SERVICIOS_ELECTRONICOS,
  PERSONAS_ASOCIADAS,
  CAMBIO_DE_NOMBRE,
  CUENTAS_TRASLADOS,
  CAMBIO_DE_IDENTIFICACION
}
