export enum ClientFormSection {
  TIPO_PERSONA_IDENTIFICACION,
  DATOS_GENERALES,
  PERFIL_ECONOMICO,
  REPRESENTANTE_LEGAL,
  DATOS_ADICIONALES,
  DOCUMENTOS,
  DIRECCIONES,
  REFERENCIAS,
  CAMBIO_DE_NOMBRE,
  CAMBIO_DE_IDENTIFICACION
}
